### ISSUE TITLE
Elaborate on homework 6 rubric

### ISSUE THREAD

**Issue by andyjko** [andyjko/hcid520#14]
* How good of an idea was it? How clear was the motivation?
* Requiring in the homework prompt that they think about use case
* Somehow capture exceptional coherence description, not just penalizing for failures
* How novel was it? How incremental was it?

**Comment by ewhitmire** [comment]
Also consider capturing the creativity of the solution. Did they simply add some polish to an existing research paper or did they synthesize the technique and apply it in a creative way?

**Comment by andyjko** [comment]
Added several new criteria.
